// unnamed.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module unnamed (
		input  wire        clk_clk,                              //                      clk.clk
		output wire        clock_bridge_sys_out_clk_clk,         // clock_bridge_sys_out_clk.clk
		input  wire        modular_adc_0_command_valid,          //    modular_adc_0_command.valid
		input  wire [4:0]  modular_adc_0_command_channel,        //                         .channel
		input  wire        modular_adc_0_command_startofpacket,  //                         .startofpacket
		input  wire        modular_adc_0_command_endofpacket,    //                         .endofpacket
		output wire        modular_adc_0_command_ready,          //                         .ready
		output wire        modular_adc_0_response_valid,         //   modular_adc_0_response.valid
		output wire [4:0]  modular_adc_0_response_channel,       //                         .channel
		output wire [11:0] modular_adc_0_response_data,          //                         .data
		output wire        modular_adc_0_response_startofpacket, //                         .startofpacket
		output wire        modular_adc_0_response_endofpacket,   //                         .endofpacket
		input  wire        reset_reset_n                         //                    reset.reset_n
	);

	unnamed_qsys_0 qsys_0 (
		.clk_clk                              (clk_clk),                              //                      clk.clk
		.clock_bridge_sys_out_clk_clk         (clock_bridge_sys_out_clk_clk),         // clock_bridge_sys_out_clk.clk
		.modular_adc_0_command_valid          (modular_adc_0_command_valid),          //    modular_adc_0_command.valid
		.modular_adc_0_command_channel        (modular_adc_0_command_channel),        //                         .channel
		.modular_adc_0_command_startofpacket  (modular_adc_0_command_startofpacket),  //                         .startofpacket
		.modular_adc_0_command_endofpacket    (modular_adc_0_command_endofpacket),    //                         .endofpacket
		.modular_adc_0_command_ready          (modular_adc_0_command_ready),          //                         .ready
		.modular_adc_0_response_valid         (modular_adc_0_response_valid),         //   modular_adc_0_response.valid
		.modular_adc_0_response_channel       (modular_adc_0_response_channel),       //                         .channel
		.modular_adc_0_response_data          (modular_adc_0_response_data),          //                         .data
		.modular_adc_0_response_startofpacket (modular_adc_0_response_startofpacket), //                         .startofpacket
		.modular_adc_0_response_endofpacket   (modular_adc_0_response_endofpacket),   //                         .endofpacket
		.reset_reset_n                        (reset_reset_n)                         //                    reset.reset_n
	);

endmodule
